version: '3.8'
services:
  delivery_service_db:
    image: postgres:latest
    container_name: delivery_service_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - ./delivery.sql:/docker-entrypoint-initdb.d/delivery.sql
    networks:
      - dbnet

volumes:
  database_postgres:

networks:
  dbnet:
    driver: bridge
