server:
  address: ":8085"
  readTime: "5s"
  writeTime: "5s"
  idleTime: "5m"
  readerHeaderTime: "5s"

services:
  accounting: "http://localhost:8080"
  restaurant: "http://localhost:8086"

database:
  host: "localhost"
  port: 5435
  user: "order_db"
  password: "order_db_pass"
  dbName: "order_db"
  sslmode: "disable"
