version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: order_service_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - ./order.sql:/docker-entrypoint-initdb.d/order.sql
