basePath: /v1
consumes:
- application/json
definitions:
  OrderData:
    properties:
      FromUserID:
        format: int64
        type: integer
      OrderItems:
        items:
          format: int64
          type: integer
        type: array
      RestaurantID:
        format: int64
        type: integer
    required:
    - FromUserID
    - RestaurantID
    - OrderItems
    title: OrderData contains information about created order.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/order/api/v1/orderapi
  OrderFilters:
    properties:
      ExcludeStatuses:
        items:
          type: string
        type: array
      FromRestaurantID:
        format: int64
        type: integer
      Statuses:
        items:
          type: string
        type: array
    title: OrderFilters struct lets user determine which orders they want to see.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/order/api/v1/orderapi
  OrderStatusData:
    properties:
      Status:
        type: string
    required:
    - Status
    title: OrderStatusData is used by admins to update current order status.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/order/api/v1/orderapi
  ReturnOrder:
    properties:
      FromUserID:
        format: int64
        type: integer
      OrderID:
        format: int64
        type: integer
      OrderItems:
        items:
          format: int64
          type: integer
        type: array
      RestaurantID:
        format: int64
        type: integer
      Status:
        type: string
    title: ReturnOrder contains order information.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/order/api/v1/orderapi
  ReturnOrderList:
    properties:
      Orders:
        description: all the requested orders
        items:
          $ref: '#/definitions/ReturnOrder'
        type: array
    title: ReturnOrderList contains information about all the requested orders.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/order/api/v1/orderapi
  Tasks:
    properties:
      Tasks: {}
    title: Tasks contains information about what number of what dishes must be prepared.
    type: object
    x-go-package: github.com/nndergunov/deliveryApp/app/services/kitchen/api/v1/kitchenapi
host: localhost:8084
info:
  description: API specification of the kitchen service
  title: Kitchen Service API V1.
  version: 0.0.1
paths:
  /tasks/{id}:
    get:
      description: Returns tasks for the specified restaurant
      operationId: returnTasks
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: requested data
          schema:
            $ref: '#/definitions/Tasks'
produces:
- application/json
schemes:
- http
swagger: "2.0"
