update-gomod-all:
	make -C ./accounting/ update-gomod
	make -C ./consumer/ update-gomod
	make -C ./courier/ update-gomod
	make -C ./delivery/ update-gomod
	make -C ./kitchen/ update-gomod
	make -C ./order/ update-gomod
	make -C ./restaurant/ update-gomod

download-gomod-all:
	make -C ./accounting/ download-gomod
	make -C ./consumer/ download-gomod
	make -C ./courier/ download-gomod
	make -C ./delivery/ download-gomod
	make -C ./kitchen/ download-gomod
	make -C ./order/ download-gomod
	make -C ./restaurant/ download-gomod

gomod-tidy-all:
	make -C ./accounting/ gomod-tidy
	make -C ./consumer/ gomod-tidy
	make -C ./courier/ gomod-tidy
	make -C ./delivery/ gomod-tidy
	make -C ./kitchen/ gomod-tidy
	make -C ./order/ gomod-tidy
	make -C ./restaurant/ gomod-tidy
