version: '3.8'
services:
  courier_service_db:
    image: postgres:latest
    container_name: courier_service_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./courier.sql:/docker-entrypoint-initdb.d/courier.sql
    networks:
      - dbnet

volumes:
  database_postgres:

networks:
  dbnet:
    driver: bridge
