server:
  rest:
    address: ":8083"
    readTime: "5s"
    writeTime: "5s"
    idleTime: "5m"
    readerHeaderTime: "5s"
  grpc:
    address: ":443"

database:
  host: "host.docker.internal"
  port: 5433
  user: "delivery_db"
  password: "delivery_db_pass"
  dbName: "delivery_db"
  sslmode: "disable"

consumerServiceURl: 127.0.0.1:441
courierServiceURl: 127.0.0.1:442
restaurantServiceURl: 127.0.0.1:446
googleApiKey: