server:
  rest:
    address: ":8083"
    readTime: "5s"
    writeTime: "5s"
    idleTime: "5m"
    readerHeaderTime: "5s"
  grpc:
    address: ":443"

database:
  host: "host.docker.internal"
  port: 5433
  user: "delivery_db"
  password: "delivery_db_pass"
  dbName: "delivery_db"
  sslmode: "disable"

consumerServiceURl: http://consumer-service:7071
courierServiceURl: http://courier-service:7072
restaurantServiceURl: http://restaurant-service:7076
googleApiKey: